### ISSUE TITLE
Default password is not working

### ISSUE THREAD

**Issue by vparonov** [poppy-project/poppy_controllers#1]
The provided username / password combination - pi / poppy is not working.
Which credentials should I use?

**Comment by ymollard** [comment]
Try `pi`/`raspberry`, or tell us exactly what image you are using.
By the way the Melodic image here is deprecated, the [latest image for the Ergo Jr](https://github.com/poppy-project/poppy-ergo-jr/releases/) now embeds ROS Noetic.

**Comment by vparonov** [comment]
Thank you for the quick response.
If this image is deprecated, I will use the last Ergo Jr image.

**Comment by ymollard** [comment]
I close this issue. Check out the ROS documentation online for software v4.0.2: https://docs.poppy-project.org/en/programming/ros.html
